# Введение в Python

![blah](https://www.python.org/static/community_logos/python-logo-inkscape.svg)

Python является языком программирования **высокого уровня** **общего назначения**. Его философия дизайна направлена на **читаемость кода**, и его синтаксис позволяет программистам выражать понятия в ** меньшем числе строк кода **, чем это возможно в таких языках, как C ++ или Java. Язык предоставляет конструкции, предназначенные для создания хорошо читаемых программ как маленького, так и большого размера

Он был разработан Guido van Rossum

![Guido](https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Guido_van_Rossum_OSCON_2006.jpg/220px-Guido_van_Rossum_OSCON_2006.jpg)

Jupyter (JUlia-PYThon-R) блокнот - это веб-приложение, которое позволяет создавать и распространять документы, которые содержат код, уравнения, визуализацию и текст.

## Комментирование вашего кода

Если хотите создать строку с комментарием, используйте символ хэштега

```Python
# Это комментарий
```

Всегда комментируйте, что вы делайте!

## Основы блокнота

Ctrl + s = сохранить документ

Ctrol + enter = запустить


## Но давайте начнем все же с самого Python


In [1]:
# Python может быть калькулятором

print (2 + 2)
print (5 - 3)
print (5 * 6)
print (16 / 8)
print (2 ** 5)
print (12 % 5) # остаток от деления

4
2
30
2.0
32
2


In [0]:
# Мы его также можем использовать как текстовый редактор

print ("Hello World!") 

Hello World!


In [0]:
# Мы можем сравнивать и оценивать выражения в виде логических знаков

# == равно
# != не равно
# >, <, >=, <= сравнения больше\меньше

print (2 + 2 == 4) 
print ("Paris" == "The Capital of Great Britain")

True
False


In [0]:
# Мы используем \n для разделения строк (переход на новую строчку)
print ("Knock knock\nWho’s there?\nMerry.\nMerry who?\nMerry Christmas!")

Knock knock
Who’s there?
Merry.
Merry who?
Merry Christmas!


In [0]:
# Но чтобы получить максимальную пользу, мы будем работать с переменными. Они могут быть различных типов:

# Числовая перменная: целое число
answer = 42 
type(answer)

int

In [0]:
# Числовая переменная: число с плавающей запятой 
pi  =  3.14159265358979323846264338327950288419716939937510

type(pi)

float

In [0]:
# Строковая переменная
language_we_learn = "Python"
type(language_we_learn)

str

In [0]:
# Список (лист)
list_of_things = [1, 2, 3, 4, "elephant"]
type(list_of_things)

list

In [0]:
# Словарь
US_presidents_age = {"Trump" : 70, "Obama" : 55, "Bush" : 70, "Сlinton" : "seventy"}

type(US_presidents_age)

dict

In [0]:
# Мы не можем сделать много с самими числами, но используя строки и списки мы можем получить следующее:

print (language_we_learn[3]) # Возвращает четвертый элемент этой строки. Стоит отметить, что отчет индексов идет с 0 в Python
print (len (list_of_things)) # Возвращает длину списка 

short_list_of_things = list_of_things[0:4] # We can assign the part of the existing list to a new list. This is called slicing
print (min (short_list_of_things)) # Возвращает максимальное значение в списке
print (max (short_list_of_things)) # Возвращает минимальное значение в списке


h
5
1
4


In [0]:
# В то время как строки неизменны (immutable, их нельзя изменить), списки изменяемы и мы можем добавить, удалить или заменить переменные внутри списка

short_list_of_things.append("Elephant") # добавляем новый элемент в список
print (short_list_of_things)
print (short_list_of_things.index("Elephant")) # проверям индекс (позицию) элемента 'Elephant' в списке

[1, 2, 3, 4, 'Elephant']
4


In [0]:
# С помощью команды .append мы добавляем новый элемент в конец списка по умолчанию. Однако, мы можем
# вставить его в любую доступную позицию 
short_list_of_things.insert(0, short_list_of_things[4]) 
print (short_list_of_things)

['Elephant', 1, 2, 3, 4, 'Elephant']


In [0]:
# Мы также можем убрать элементы из списка
short_list_of_things.remove("Elephant")
print (short_list_of_things)

[1, 2, 3, 4, 'Elephant']


In [0]:
# Есть и другой способ убрать элемент из списка
del short_list_of_things[4]
print (short_list_of_things)

[1, 2, 3, 4]


## Индексирование / Разделение

In [0]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [0]:
# Используя квадратные скобки, мы получаем значение в указанном индексе переменной. Напоминаем, что индексирование начинается с 0
s[0], s[4], s[-1]

(0, 16, 144)

In [0]:
# Используем : для обозначения диапазона. array[start:stop], не указывая start или stop, мы говорим использовать начало\конец массива.
s[1:5]

array([ 1,  4,  9, 16])

In [0]:
# Используем отрицательные индексы для отчета от конца массива
s[-4:]

array([ 81, 100, 121, 144])

In [0]:
# Также его можно использовать как шаг - array[start:stop:stepsize]
# Тут мы начинаем с пятого элемента с конца и двигаемся вперед к началу массива с шагом 2
s[-5::-2]

array([64, 36, 16,  4,  0])

## Числа

In [4]:
# Для работы с числами, мы можем воспользоваться многичисленным операциями
# Для удобства сразу выведем на экран результаты вычислений

print(123 + 222) # Целочисленное сложение

print(1.5 * 4) # Умножение вещественных чисел

print(2 ** 100) # 2 в степени 100

345
6.0
1267650600228229401496703205376


6.283

In [5]:
# Помимо выражений для выполнения операций с числами в составе Python есть несколько полезных модулей:

import math # через функцию импорта мы загружаем дополнительные модули, которые позволяют нам выполнять дополнительные операции
math.pi # Это, например, вывод числа Pi

3.141592653589793

In [6]:
math.sqrt(85) # А это квадратный корень числа 85

9.219544457292887

## Строки

In [0]:
# Несмотря на то что строки неизменны, над ними можно совершать различные операции 

yt_pos = language_we_learn.find("yt") # метод .find возвращает индекс элемента строки с которого начинается указанная подстрока

print (yt_pos)

1


In [0]:
x = 'This is a string'
print(x[0]) # первый символ
print(x[0:1]) # первый символ, но мы конкретно указали конечный символ ( грубо говоря диапазон)
print(x[0:2]) # первые два символа

T
T
Th


In [0]:
# Мы можем применять разделение и на строки

print (language_we_learn[yt_pos:])
print (language_we_learn[yt_pos : len(language_we_learn) - 1]) # метод len возращает длину строки

ython
ytho


In [0]:
animals = "catdogfrog"
c  = animals[:3]   # первые три символа
d  = animals[3:6]  # с четвертого по шестой символы
f = animals[6:len(animals)]   

print(c,d,f)

cat dog frog


In [0]:
parrot = "Norwegian Blue"

print(parrot.lower()) # метод приводит все символы к нижнему регистру


norwegian blue


In [0]:
ministry = "The Ministry of Silly Walks"

print(len(ministry))
print(ministry.upper()) # метод приводит все символы к верхнему регистру

27
THE MINISTRY OF SILLY WALKS


In [3]:
name = input("What is your name?")
surname = input("What is your surname?")
color = input("What is your favorite color?")

print ("Ah, so your name is %s, your surname is %s, " \
"and your favorite color is %s." % (name, surname, color))

What is your name?Tanya
What is your surname?Rogovich
What is your favorite color?Blue
Ah, so your name is Tanya, your surname is Rogovich, and your favorite color is Blue.


In [0]:
firstname = 'Tatiana'
lastname = 'Rogovich'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Tatiana' in firstname)


Tatiana Rogovich
TatianaTatianaTatiana
True


In [7]:
# Наконец, будучи последовательностями, строки поддерживают операцию конкатенации, которая записывается в виде знака плюс (объединение двух строк
# в одну строку), и операцию повторения (новая строка создается за счет многократного повторения другой строки):
S = 'Spam'
S2 = S + 'xyz' # Конкатенация
S3 = S * 8 # Повторение

print(S)
print(S2)
print(S3)

# Обратите внимание, что знак плюс (+) имеет различное значение для разных
# объектов: для чисел – сложение, а для строк – конкатенация.

Spam
Spamxyz
SpamSpamSpamSpamSpamSpamSpamSpam


In [8]:
line = 'aaa,bbb,ccccc,dd'
line.split(',') # Разбивает строку по разделителю и создает список строк ['aaa', 'bbb', 'ccccc', 'dd']

['aaa', 'bbb', 'ccccc', 'dd']

In [0]:
# В Python мы можем спросить у пользователя ввод данных

number = random.randrange (1,10) # для запуска этой команды, нам нужен обратиться к самому модулю и вызвать нужный метод - имя_модуля.имя_метода
guessed_number = int(input("Guess the number: "))

print ("The generated number was: %s" %(number)) # %s это заместитель строки (что мы выводим в строке переменную), %() это оператор, который показывает, какую переменную нужно ввести


Guess the number: 4
The generated number was: 8


## Списки

In [10]:
# Поскольку списки являются последовательностями, они поддерживают все операции над последовательностями.
# Единственное отличие состоит в том, что результатом таких операций являются списки, а не строки.

L = [123, 'spam', 1.23] # Список из трех объектов разных типов
len(L) # Число элементов в списке

3

In [11]:
# Мы можем обращаться к элементам списка по их индексам, получать срезы
# и так далее, точно так же, как и в случае со строками:

L[0] # Доступ к элементу списка по его индексу

123

In [12]:
L[:-1] # Операция получения среза возвращает новый список

[123, 'spam']

In [13]:
L + [4, 5, 6] # Операция конкатенации также возвращает новый список

[123, 'spam', 1.23, 4, 5, 6]

In [17]:
L.append('NI') # Увеличение: в конец списка добавляется новый объект
L

[123, 'spam', 1.23, 'NI', 'NI', 'NI']

In [18]:
L.pop(2) # Уменьшение: удаляется элемент из середины списка

1.23

In [19]:
# Списки можно сортировать

M = ['bb', 'aa', 'cc']
M.sort()
M

['aa', 'bb', 'cc']

In [20]:
M.reverse()
M

# Метод sort, использованный в этом примере, по умолчанию упорядочивает элементы списка по возрастанию, 
# а метод reverse – по убыванию. В обоих случаях происходит непосредственное изменение самого списка.

['cc', 'bb', 'aa']

In [23]:
# Можно создавать вложенные списки

M = [[1, 2, 3], # Матрица 3 x 3 в виде вложенных списков
[4, 5, 6], # Выражение в квадратных скобках может
[7, 8, 9]] # занимать несколько строк

M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Словари

In [0]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Получаем значение с помощью оператора индексирования (квадратных скобок)


'brooksch@umich.edu'

In [0]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com


In [0]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com


In [0]:
menu = {} # Пустой словарь
menu['Chicken Alfredo'] = 14.50 # Добавляем новую пару ключ-значение
print (menu['Chicken Alfredo'])

14.5
There are 4 items on the menu.
{'Coffee': 3.5, 'Chicken Alfredo': 14.5, 'Udon': 20.0, 'Tea': 2.0}


In [0]:
menu['Udon'] = 20.00
menu['Coffee'] = 3.50
menu['Tea'] = 2.00



print ("There are " + str(len(menu)) + " items on the menu.")
print (menu)

There are 4 items on the menu.
{'Coffee': 3.5, 'Chicken Alfredo': 14.5, 'Udon': 20.0, 'Tea': 2.0}


## Конструкции  if-elif-else


In [3]:
# Пример работы с условными кострукциями if

a = 3
if a == 3: # проверяем корректность условия и выполняем код, если оно верно
    print("hello 2")

hello 2


In [1]:
# Пример работы с условными кострукциями if-else

amount = int(input("Enter amount: ")) # вводим число


if amount<1000: #проверяем условие (введеное число меньше 1000)
   discount = amount*0.05 # далее идет код, который исполняется при удовлетворении
   print ("Discount",discount) #условия
else: # дальше идет опциональная часть кода, которая исполняется если условие НЕ выполнено
   discount = amount*0.10
   print ("Discount",discount)
    
print ("Net payable:",amount-discount)


Enter amount: 986
Discount 49.300000000000004
Net payable: 936.7


In [2]:
# Пример работы с условными кострукциями if-else-elif

amount = int(input("Enter amount: ")) # вводим число


if amount<1000: #проверяем условие (введеное число меньше 1000)
   discount = amount*0.05
   print ("Discount",discount)
elif amount<5000: # если первое условие не выполнено, то проверяем второе условие
   discount = amount*0.10 # и выполняет данный код при его удовлетворении
   print ("Discount",discount)
else: # если же оба условия не выполнены, то выполняем эту часть кода
   discount = amount*0.15
   print ("Discount",discount)
  
# Стоит отметить,что количество блоков elif может быть любым
    
print ("Net payable:",amount-discount)

Enter amount: 3203
Discount 320.3
Net payable: 2882.7


In [6]:
# Пример работы с условными кострукциями if-else-elif вложенными друг в друга
# Одно условия можно вставлять внутрь другого, главное при этом не запутаться

num = int(input("Enter number: "))

if num > 100:
    if num < 150:
        print("Число больше ста, но меньше ста пятидесяти")
    elif num < 200:
        print("Число больше ста, но меньше двухсот")
elif num > 50:
    if num < 90:
        print("Число больше пятидесяти, но меньше девяноста")
    else:
        print("Число больше пятидесяти и больше девяноста")
else:
    print("Число меньше пятидесяти")

Enter number: 120
Число больше ста, но меньше ста пятидесяти


## Функции

In [0]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


In [0]:
def greater_less_equal_5(answer):
    if answer > 5:
        return 1
    elif answer <5 :          
        return -1
    else:
        return 0
        
print (greater_less_equal_5(4))
print (greater_less_equal_5(5))
print (greater_less_equal_5(6))

-1
0
1


In [0]:
def power(base,exponent):  # Добавьте свои параметры здесь
    result = base**exponent
    print ("%d to the power of %d is %d." % (base, exponent, result))

power(37,4)  # Добавьте свои аргументы здесь

37 to the power of 4 is 1874161.


In [0]:
def distance_from_zero(x):
    if type(x) == int or type(x) == float :
        return abs(x)
    else:
        return 'Wrong Entry'
    
distance_from_zero(-12)


12

In [0]:
distance_from_zero('ewag')

'Wrong Entry'

## For Loop (Циклы)

In [0]:
my_list = [1,9,3,8,5,7]

for number in my_list:
    print (2*number)

2
18
6
16
10
14


In [0]:
start_list = [5, 3, 1, 2, 4]
square_list = []

for number in start_list:
    square_list.append(number ** 2)
print (square_list)

[25, 9, 1, 4, 16]


In [0]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

for number in a:
    if number % 2 == 0:
        print (number)
    else : continue

0
2
4
6
8
10
12


In [24]:
for c in 'spam':
  print(c.upper())

S
P
A
M


## While (Циклы)

In [26]:
# Цикл while в языке Python представляет собой более универсальный инструмент
# выполнения циклически повторяющихся операций и не имеет прямой связи с последовательностями:

x = 4
while x > 0:
  print('spam!' * x)
  x -= 1


spam!spam!spam!spam!
spam!spam!spam!
spam!spam!
spam!


In [0]:
# Пример бесконечно цикла, этот код будет выполняться бесконечно, так как
# условие всегда верно.
# (Пожалуйста, НЕ запускайте данный код)

a = 0
while a == 0:
   print("A")

In [7]:
# При работе с циклами используются операторы break и continue.
# Как раз для предотвращения ситуации с бесконечным циклом
# Оператор break  предназначен для досрочного прерывания работы цикла while.

a = 0
while a >= 0:
   if a == 7:
       break
   a += 1 # мы увеличиваем счетчик каждй раз на 1 и в какой-то момент он станет равен 7
   print("A") # и прерветься

# без этого условия, цикл будет работать бесконечно

A
A
A
A
A
A
A


In [8]:
# Оператор continue  запускает цикл заново, при этом код, 
# расположенный после данного оператора, не выполняется.

a = -1
while a < 10:
   a += 1
   if a >= 7:
       continue
   print("A")
  
  # При запуске данного кода символ “А” будет напечатан 7 раз, 
  # несмотря на то, что всего будет выполнено 11 проходов цикла.

A
A
A
A
A
A
A


In [11]:
# Бесконечный цикл также можно сделать просто указав True в качестве условия
# Но нужно убедиться что выход из цикла есть

a = 3

while True:
  a += 2
  if a == 11:
    break
  print(a)
    
# Обычно цикл while используется, когда не известно точное количество проходов по циклу
# или по время рекурсий
  

5
7
9


## Математические функции
<br>
NumPy встроенные математические функции

In [0]:
a = np.array([-4, -2, 1, 3, 5])

In [0]:
a.sum()

3

In [0]:
a.max()

5

In [0]:
a.min()

-4

In [0]:
a.mean()

0.59999999999999998

In [0]:
a.std()

3.2619012860600183